version: "3.8"

services:
  web:
    build: .
    entrypoint: ./entrypoint.sh
    volumes:
      - .:/web_django
    ports:
      - "12000:8000"
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
    - "5532:5432"
  mongo:
    image: mongo
    ports:
    - "27020:27017"
volumes:
  postgres_data: