version: "3.8"

services:
  web:
    tty: true
    stdin_open: true
    build: .
    entrypoint: ./entrypoint.sh
    volumes:
      - .:/web_django
    ports:
      - "12000:8000"
    depends_on:
      - db
  db:
    image: postgres:14.0-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_DB: bbdd2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
    - "5532:5432"
  mongo:
    image: mongo
    ports:
    - "27020:27017"
volumes:
  postgres_data: