# Generated by Django 4.1.3 on 2022-12-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_flightprice_legid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightprice',
            name='legId',
            field=models.TextField(),
        ),
    ]
